sudo: required
language: java
services:
  - docker
before_install:
  - ./gradlew clean
before_deploy:
- ./gradlew generatePomFileForMavenPublication
after_success:
- bash <(curl -s https://codecov.io/bash)
